const productData = [
    {
        id: 1,
        name: 'Mô hình căn nhà',
        price: 20000,
        oldPrice: 30000,
        discount: '39%',
        category: 'Mô hình đồ chơi',
        brand: 'Model world',
        promotion: 0,
        remaining: 9,
        shipFrom: 'Cần Thơ',
        images: [
            '../../../public/assets/client/images/images11.jpg',
            '../../../public/assets/client/images/images11.jpg',
            '../../../public/assets/client/images/images11.jpg',
            '../../../public/assets/client/images/images11.jpg',
        ],
        description:
            'Mô hình nhà ở chế tác từ chất liệu nhựa cao cấp, an toàn, và bền bỉ, thiết kế chi tiết và tinh xảo. Sản phẩm này không chỉ là một món đồ chơi giải trí mà còn giúp kích thích sự sáng tạo và phát triển kỹ năng tư duy cho trẻ em. Với mô hình này, trẻ có thể học cách lắp ráp và khám phá cấu trúc một ngôi nhà, mang lại giờ phút vui chơi lành mạnh và bổ ích.',
    },
    {
        id: 2,
        name: 'Mô hình xe ô tô',
        price: 15000,
        oldPrice: 25000,
        discount: '40%',
        category: 'Mô hình đồ chơi',
        brand: 'Model world',
        promotion: 0,
        remaining: '9',
        shipFrom: 'Cần Thơ',
        image: '../../../public/assets/client/images/images11.jpg',
    },
    {
        id: 3,
        name: 'Mô hình máy bay',
        price: 25000,
        oldPrice: 40000,
        discount: '37%',
        category: 'Mô hình đồ chơi',
        brand: 'Model world',
        promotion: 0,
        remaining: '9',
        shipFrom: 'Cần Thơ',
        image: '../../../public/assets/client/images/images11.jpg',
    },
    {
        id: 4,
        name: 'Mô hình tàu lửa',
        price: 30000,
        oldPrice: 50000,
        discount: '35%',
        category: 'Mô hình đồ chơi',
        brand: 'Model world',
        promotion: 0,
        remaining: '9',
        shipFrom: 'Cần Thơ',
        image: '../../../public/assets/client/images/images11.jpg',
    },
    {
        id: 5,
        name: 'Mô hình xe máy',
        price: 18000,
        oldPrice: 28000,
        discount: '36%',
        category: 'Mô hình đồ chơi',
        brand: 'Model world',
        promotion: 0,
        remaining: '9',
        shipFrom: 'Cần Thơ',
        image: '../../../public/assets/client/images/images11.jpg',
    },
    {
        id: 6,
        name: 'Mô hình tàu thuyền',
        price: 22000,
        oldPrice: 35000,
        discount: '37%',
        category: 'Mô hình đồ chơi',
        brand: 'Model world',
        promotion: 0,
        remaining: '9',
        shipFrom: 'Cần Thơ',
        image: '../../../public/assets/client/images/images11.jpg',
    },
];

export default productData;
